---
- name: install the iis web service
  hosts: all

  tasks:
    - name: install and enable iis
      win_feature:
        name: Web-Server
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes

    - name: Create website index.html
      win_copy:
        content: "{{ iis_test_message }}"
        dest: 'C:\Inetpub\wwwroot\index.html'
